apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web
  namespace: {{ .Release.Namespace }}
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: devops-web
  template:
    metadata:
      labels:
        app: devops-web
    spec:
      containers:
        - name: devops-web
          image: container.simafig.com/devops/devops-web:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
      imagePullSecrets:
        - name: container.simafig.com
      
