apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devops-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sandbox.aktivecloud.com
    http:
      paths:
      - backend:
          serviceName: devops-svc
          servicePort: 80
