kind: Service
apiVersion: v1
metadata:
  labels:
    app: devops-web
  name: devops-svc-nodeport
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: devops-web
  ports:
    - port: 80           
      nodePort: 30080   #range  30000-32767
      targetPort: 80
      name: http  
